### ISSUE TITLE
CORS upload to Rackspace Cloud Files

### ISSUE THREAD

**Issue by secretfader** [pkgcloud/pkgcloud#279]
As it stands, I don't see a convenient way to sign CORS requests to Rackspace Cloud Files. This would be a very awesome feature.

For reference, here's how the client for Joyent's Manta storage service handles request signing. This is just an example of how somebody else does it, not a request that you change existing APIs. Just expose existing ones. :)

https://github.com/nicholaswyoung/manta-cors-express/blob/master/index.js

**Comment by 26medias** [comment]
So it's been over a year, and it's still a pretty big issue, as webfonts can't be hosted on the cloud for example.
Can we get an update?
Or at least a solution too implement it on our side?

**Comment by 26medias** [comment]
Since this is clearly not coming any time soon, I've written a package that will make your containers and files CORS compatible:

https://www.npmjs.com/package/cloudfile-cors
https://github.com/26medias/cloudfile-cors

That fixed the issue for us, and now we can finally enjoy AngularJS views hosted on Rackspace Cloud Files without issues.
